AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Bucket template

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'

# These output values are will be available to service templates, given the
# the 'environment' namespace, for example, environment.outputs.ClusterName.
Outputs:
  BucketName:
    Description: S3 bucket name
    Value: !Ref S3Bucket

  #DnsHostname:
  #  Description: The DNS hostname of the hosted zone
  #  Value: '{{ environment.inputs.dns_hostname }}'